services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketing_platform
      MYSQL_USER: ticketing
      MYSQL_PASSWORD: ticketing
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./BD/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./BD/seed_lima.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uticketing", "-pticketing"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: ./api
    ports:
      - "8080:80"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ticketing_platform
      DB_USER: ticketing
      DB_PASSWORD: ticketing
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: